project:
  type: website
  output-dir: results
  render: 
    - notebooks/COVID_time_analysis.qmd

website:
  title: "."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: yeti
    css: styles.css
    self-contained: true
    grid:
      body-width: 1800px
    anchor-sections: true
    code-fold: true
    code-overflow: wrap

